{% set version = "1.1.7" %}

package:
  name: imgurpython
  version: {{ version }}

source:
  fn: imgurpython-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/imgurpython/imgurpython-{{ version }}.tar.gz
  md5: f2eb3a55c495d80812bae2238721da06

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - requests
  run:
    - python
    - requests

test:
  imports:
    - imgurpython
    - imgurpython.helpers
    - imgurpython.imgur
    - imgurpython.imgur.models

about:
  home: https://github.com/Imgur/imgurpython
  license: MIT
  summary: 'Official Imgur python library with OAuth2 and samples'

extra:
  recipe-maintainers:
    - asmeurer
