travis:
  secure:
    BINSTAR_TOKEN: Wf7baY8ZW8gnEBWeaw/9BMH7YRGLt0V80zfhJG4eDQZvtRY4qZF67CqnLEzM2XISmYb0285DIHhBzvVFKGcPuq5NQtpXdi1UjAZOvbTDPJYh3i8EBad/jtMOCiJyzO90AvQfoQgr7uDSn1/ILGqIF/pFvHq+p6o5nEEnROkxtkJzenC02cX4/r0AqHKOuBFbyWeqijqWBmCha1J8+krnN+68JbdAufYs/hW6Rh+2vP6f43hZw7LBL/DVJ1Iqfo+kjrizrbrJ+M9gjNN3s4tUSUsa9rsWfzbT76JahEDe1Jbgt0rmb1fylOWwKcT4Wf+5XSiCuz7naQpCVIZIoCur0AFeQj9r/q43A+8tN1btJ4izGmNXbPNjhR3DAmviQ95ReK45Oh6dnBCTECHkTs6INx+YW5jXThEGhSZLRSswDtgX5opKiUrf/7QtZdCDa6EaAr+2cUHsZsqlk6g4dwtY/RehlOLcr4RAGSK9jEu2HHgQvMJpm5Kv+lCOe6FwNFPI/0mwH1ObM5ExRKEysehZ3lU5iW/vYAJabI1QTun4NiwmnaLZfPEvLRPRdVANmcNoh4L6wWAofBzwvveJMEiPghT9dZWDA3dEmwosfBW2URcNAzonS/0Aib0GT7mpp/IGrPR7Mx8QwK8ImJg9+/OcRaLVqVQcmrH7HvnlYbSHwd4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
